### ISSUE TITLE
Can you recognize multiple codes at the same time

### ISSUE THREAD

**Issue by wang94** [markusfisch/CameraView#5]
Whether multiple codes can be identified in the scanning interface, and then click Identify

**Comment by markusfisch** [comment]
This is just a camera view - not a scanning library. I suspect this issue applies to [BarcodeScannerView](https://github.com/markusfisch/BarcodeScannerView)?

Where the answer would be no, unfortunately, because `BarcodeScannerView` is [configured](https://github.com/markusfisch/BarcodeScannerView/blob/main/barcodescannerview/src/main/java/de/markusfisch/android/barcodescannerview/widget/BarcodeScannerView.java#L207C23-L207C23) to scan only one symbol at the moment. But this could be changed, of course, because [ZXing C++](https://github.com/zxing-cpp/zxing-cpp), the barcode scanning library that is used, supports scanning multiple barcodes in one frame.
